apiVersion: v1
kind: Service
metadata:
  name: jobly-api-service
  labels:
    app: jobly-api
spec:
  type: ClusterIP
  selector:
    app: jobly-api
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
      name: http
