apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobly-web
  labels:
    app: jobly-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jobly-web
  template:
    metadata:
      labels:
        app: jobly-web
    spec:
      containers:
      - name: jobly-web
        image: jobly-web:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: VITE_API_URL
          value: "http://jobly-api:5000"
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "300m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: jobly-web
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: jobly-web
