FROM node:22-alpine AS builder

# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat

WORKDIR /app

# Install dependencies based on the preferred package manager
COPY package.json package-lock.json* ./
# We also need to copy the contracts package since it's a local dependency via workspace or file protocol
COPY ../packages/contracts ../packages/contracts

RUN npm ci

# Copy application code
COPY . .

# Build the application (Nitro/Tanstack build)
RUN npm run build

# Production image, copy all the files and run nitro server
FROM node:22-alpine AS runner
WORKDIR /app

ENV NODE_ENV production
ENV PORT 3000

# Copy the built output from builder
COPY --from=builder /app/.output ./.output
COPY --from=builder /app/public ./public

# Expose port
EXPOSE 3000

# Start the nitro server generated by Tanstack Start build
CMD ["node", ".output/server/index.mjs"]
