/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FocusSessionIdRouteImport } from './routes/focus.$sessionId'
import { Route as CompeteLobbyIdRouteImport } from './routes/compete.$lobbyId'
import { Route as AppResumeRouteImport } from './routes/_app.resume'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppPostJobRouteImport } from './routes/_app.post-job'
import { Route as AppMessagesRouteImport } from './routes/_app.messages'
import { Route as AppLearnRouteImport } from './routes/_app.learn'
import { Route as AppJobsRouteImport } from './routes/_app.jobs'
import { Route as AppInterviewsRouteImport } from './routes/_app.interviews'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCompeteRouteImport } from './routes/_app.compete'
import { Route as AppApplicationsRouteImport } from './routes/_app.applications'
import { Route as AppApplicantsRouteImport } from './routes/_app.applicants'
import { Route as AppInterviewRoomKeyRouteImport } from './routes/_app.interview.$roomKey'
import { Route as AppInterviewRoomKeyReplayRouteImport } from './routes/_app.interview.$roomKey.replay'
import { Route as AppInterviewRoomKeyFeedbackRouteImport } from './routes/_app.interview.$roomKey.feedback'
import { Route as AppInterviewRoomKeyEvaluationRouteImport } from './routes/_app.interview.$roomKey.evaluation'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusSessionIdRoute = FocusSessionIdRouteImport.update({
  id: '/focus/$sessionId',
  path: '/focus/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const CompeteLobbyIdRoute = CompeteLobbyIdRouteImport.update({
  id: '/compete/$lobbyId',
  path: '/compete/$lobbyId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppResumeRoute = AppResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPostJobRoute = AppPostJobRouteImport.update({
  id: '/post-job',
  path: '/post-job',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppLearnRoute = AppLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppInterviewsRoute = AppInterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCompeteRoute = AppCompeteRouteImport.update({
  id: '/compete',
  path: '/compete',
  getParentRoute: () => AppRoute,
} as any)
const AppApplicationsRoute = AppApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AppRoute,
} as any)
const AppApplicantsRoute = AppApplicantsRouteImport.update({
  id: '/applicants',
  path: '/applicants',
  getParentRoute: () => AppRoute,
} as any)
const AppInterviewRoomKeyRoute = AppInterviewRoomKeyRouteImport.update({
  id: '/interview/$roomKey',
  path: '/interview/$roomKey',
  getParentRoute: () => AppRoute,
} as any)
const AppInterviewRoomKeyReplayRoute =
  AppInterviewRoomKeyReplayRouteImport.update({
    id: '/replay',
    path: '/replay',
    getParentRoute: () => AppInterviewRoomKeyRoute,
  } as any)
const AppInterviewRoomKeyFeedbackRoute =
  AppInterviewRoomKeyFeedbackRouteImport.update({
    id: '/feedback',
    path: '/feedback',
    getParentRoute: () => AppInterviewRoomKeyRoute,
  } as any)
const AppInterviewRoomKeyEvaluationRoute =
  AppInterviewRoomKeyEvaluationRouteImport.update({
    id: '/evaluation',
    path: '/evaluation',
    getParentRoute: () => AppInterviewRoomKeyRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/applicants': typeof AppApplicantsRoute
  '/applications': typeof AppApplicationsRoute
  '/compete': typeof AppCompeteRoute
  '/dashboard': typeof AppDashboardRoute
  '/interviews': typeof AppInterviewsRoute
  '/jobs': typeof AppJobsRoute
  '/learn': typeof AppLearnRoute
  '/messages': typeof AppMessagesRoute
  '/post-job': typeof AppPostJobRoute
  '/profile': typeof AppProfileRoute
  '/resume': typeof AppResumeRoute
  '/compete/$lobbyId': typeof CompeteLobbyIdRoute
  '/focus/$sessionId': typeof FocusSessionIdRoute
  '/interview/$roomKey': typeof AppInterviewRoomKeyRouteWithChildren
  '/interview/$roomKey/evaluation': typeof AppInterviewRoomKeyEvaluationRoute
  '/interview/$roomKey/feedback': typeof AppInterviewRoomKeyFeedbackRoute
  '/interview/$roomKey/replay': typeof AppInterviewRoomKeyReplayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/applicants': typeof AppApplicantsRoute
  '/applications': typeof AppApplicationsRoute
  '/compete': typeof AppCompeteRoute
  '/dashboard': typeof AppDashboardRoute
  '/interviews': typeof AppInterviewsRoute
  '/jobs': typeof AppJobsRoute
  '/learn': typeof AppLearnRoute
  '/messages': typeof AppMessagesRoute
  '/post-job': typeof AppPostJobRoute
  '/profile': typeof AppProfileRoute
  '/resume': typeof AppResumeRoute
  '/compete/$lobbyId': typeof CompeteLobbyIdRoute
  '/focus/$sessionId': typeof FocusSessionIdRoute
  '/interview/$roomKey': typeof AppInterviewRoomKeyRouteWithChildren
  '/interview/$roomKey/evaluation': typeof AppInterviewRoomKeyEvaluationRoute
  '/interview/$roomKey/feedback': typeof AppInterviewRoomKeyFeedbackRoute
  '/interview/$roomKey/replay': typeof AppInterviewRoomKeyReplayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/applicants': typeof AppApplicantsRoute
  '/_app/applications': typeof AppApplicationsRoute
  '/_app/compete': typeof AppCompeteRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/interviews': typeof AppInterviewsRoute
  '/_app/jobs': typeof AppJobsRoute
  '/_app/learn': typeof AppLearnRoute
  '/_app/messages': typeof AppMessagesRoute
  '/_app/post-job': typeof AppPostJobRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/resume': typeof AppResumeRoute
  '/compete/$lobbyId': typeof CompeteLobbyIdRoute
  '/focus/$sessionId': typeof FocusSessionIdRoute
  '/_app/interview/$roomKey': typeof AppInterviewRoomKeyRouteWithChildren
  '/_app/interview/$roomKey/evaluation': typeof AppInterviewRoomKeyEvaluationRoute
  '/_app/interview/$roomKey/feedback': typeof AppInterviewRoomKeyFeedbackRoute
  '/_app/interview/$roomKey/replay': typeof AppInterviewRoomKeyReplayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/applicants'
    | '/applications'
    | '/compete'
    | '/dashboard'
    | '/interviews'
    | '/jobs'
    | '/learn'
    | '/messages'
    | '/post-job'
    | '/profile'
    | '/resume'
    | '/compete/$lobbyId'
    | '/focus/$sessionId'
    | '/interview/$roomKey'
    | '/interview/$roomKey/evaluation'
    | '/interview/$roomKey/feedback'
    | '/interview/$roomKey/replay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/applicants'
    | '/applications'
    | '/compete'
    | '/dashboard'
    | '/interviews'
    | '/jobs'
    | '/learn'
    | '/messages'
    | '/post-job'
    | '/profile'
    | '/resume'
    | '/compete/$lobbyId'
    | '/focus/$sessionId'
    | '/interview/$roomKey'
    | '/interview/$roomKey/evaluation'
    | '/interview/$roomKey/feedback'
    | '/interview/$roomKey/replay'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/applicants'
    | '/_app/applications'
    | '/_app/compete'
    | '/_app/dashboard'
    | '/_app/interviews'
    | '/_app/jobs'
    | '/_app/learn'
    | '/_app/messages'
    | '/_app/post-job'
    | '/_app/profile'
    | '/_app/resume'
    | '/compete/$lobbyId'
    | '/focus/$sessionId'
    | '/_app/interview/$roomKey'
    | '/_app/interview/$roomKey/evaluation'
    | '/_app/interview/$roomKey/feedback'
    | '/_app/interview/$roomKey/replay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  CompeteLobbyIdRoute: typeof CompeteLobbyIdRoute
  FocusSessionIdRoute: typeof FocusSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus/$sessionId': {
      id: '/focus/$sessionId'
      path: '/focus/$sessionId'
      fullPath: '/focus/$sessionId'
      preLoaderRoute: typeof FocusSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compete/$lobbyId': {
      id: '/compete/$lobbyId'
      path: '/compete/$lobbyId'
      fullPath: '/compete/$lobbyId'
      preLoaderRoute: typeof CompeteLobbyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/resume': {
      id: '/_app/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof AppResumeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/post-job': {
      id: '/_app/post-job'
      path: '/post-job'
      fullPath: '/post-job'
      preLoaderRoute: typeof AppPostJobRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages': {
      id: '/_app/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/learn': {
      id: '/_app/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof AppLearnRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs': {
      id: '/_app/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/interviews': {
      id: '/_app/interviews'
      path: '/interviews'
      fullPath: '/interviews'
      preLoaderRoute: typeof AppInterviewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/compete': {
      id: '/_app/compete'
      path: '/compete'
      fullPath: '/compete'
      preLoaderRoute: typeof AppCompeteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/applications': {
      id: '/_app/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AppApplicationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/applicants': {
      id: '/_app/applicants'
      path: '/applicants'
      fullPath: '/applicants'
      preLoaderRoute: typeof AppApplicantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/interview/$roomKey': {
      id: '/_app/interview/$roomKey'
      path: '/interview/$roomKey'
      fullPath: '/interview/$roomKey'
      preLoaderRoute: typeof AppInterviewRoomKeyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/interview/$roomKey/replay': {
      id: '/_app/interview/$roomKey/replay'
      path: '/replay'
      fullPath: '/interview/$roomKey/replay'
      preLoaderRoute: typeof AppInterviewRoomKeyReplayRouteImport
      parentRoute: typeof AppInterviewRoomKeyRoute
    }
    '/_app/interview/$roomKey/feedback': {
      id: '/_app/interview/$roomKey/feedback'
      path: '/feedback'
      fullPath: '/interview/$roomKey/feedback'
      preLoaderRoute: typeof AppInterviewRoomKeyFeedbackRouteImport
      parentRoute: typeof AppInterviewRoomKeyRoute
    }
    '/_app/interview/$roomKey/evaluation': {
      id: '/_app/interview/$roomKey/evaluation'
      path: '/evaluation'
      fullPath: '/interview/$roomKey/evaluation'
      preLoaderRoute: typeof AppInterviewRoomKeyEvaluationRouteImport
      parentRoute: typeof AppInterviewRoomKeyRoute
    }
  }
}

interface AppInterviewRoomKeyRouteChildren {
  AppInterviewRoomKeyEvaluationRoute: typeof AppInterviewRoomKeyEvaluationRoute
  AppInterviewRoomKeyFeedbackRoute: typeof AppInterviewRoomKeyFeedbackRoute
  AppInterviewRoomKeyReplayRoute: typeof AppInterviewRoomKeyReplayRoute
}

const AppInterviewRoomKeyRouteChildren: AppInterviewRoomKeyRouteChildren = {
  AppInterviewRoomKeyEvaluationRoute: AppInterviewRoomKeyEvaluationRoute,
  AppInterviewRoomKeyFeedbackRoute: AppInterviewRoomKeyFeedbackRoute,
  AppInterviewRoomKeyReplayRoute: AppInterviewRoomKeyReplayRoute,
}

const AppInterviewRoomKeyRouteWithChildren =
  AppInterviewRoomKeyRoute._addFileChildren(AppInterviewRoomKeyRouteChildren)

interface AppRouteChildren {
  AppApplicantsRoute: typeof AppApplicantsRoute
  AppApplicationsRoute: typeof AppApplicationsRoute
  AppCompeteRoute: typeof AppCompeteRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppInterviewsRoute: typeof AppInterviewsRoute
  AppJobsRoute: typeof AppJobsRoute
  AppLearnRoute: typeof AppLearnRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppPostJobRoute: typeof AppPostJobRoute
  AppProfileRoute: typeof AppProfileRoute
  AppResumeRoute: typeof AppResumeRoute
  AppInterviewRoomKeyRoute: typeof AppInterviewRoomKeyRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppApplicantsRoute: AppApplicantsRoute,
  AppApplicationsRoute: AppApplicationsRoute,
  AppCompeteRoute: AppCompeteRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppInterviewsRoute: AppInterviewsRoute,
  AppJobsRoute: AppJobsRoute,
  AppLearnRoute: AppLearnRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppPostJobRoute: AppPostJobRoute,
  AppProfileRoute: AppProfileRoute,
  AppResumeRoute: AppResumeRoute,
  AppInterviewRoomKeyRoute: AppInterviewRoomKeyRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  CompeteLobbyIdRoute: CompeteLobbyIdRoute,
  FocusSessionIdRoute: FocusSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
