apiVersion: v1
kind: ConfigMap
metadata:
  name: jobly-config
data:
  NODE_ENV: "production"
  PORT: "5000"
  # Service discovery relies on k8s DNS
  MONGO_URI: "mongodb://jobly-mongodb:27017/jobmatch"
  REDIS_HOST: "jobly-redis-master"
  REDIS_PORT: "6379"
  S3_ENDPOINT: "http://jobly-minio:9000"
  S3_BUCKET: "jobly-resumes"
  TERMINAL_RUNNER_URL: "http://terminal-runner-service:80"
  # Web uses this to connect to API internally (SSR)
  API_URL: "http://jobly-api-service:80/api"
  VITE_API_URL: "/api"
  # When deployed, specify real WSS URL
  LIVEKIT_PUBLIC_URL: "wss://jobly.local"
