apiVersion: v1
kind: Service
metadata:
  name: jobly-web-service
  labels:
    app: jobly-web
spec:
  type: ClusterIP
  selector:
    app: jobly-web
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
